services:
  dev:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app # ローカルをコンテナ内にマウント
    command: sleep infinity
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=$DOCKER_HOST_IP_ADDRESS
    ports:
      - "8081:8081" # Expo 開発サーバー
